version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/app
    ports:
      - 3333:3333
    depends_on:
      - db
  db:
    image: postgres:10
    ports: 
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: '1234'
      POSTGRES_USER: postgres 